<a href="https://colab.research.google.com/github/HallsofLearningCoding/IAOI_Recap/blob/main/Week4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Week 4! Wohoo! Welcome to Week 4!

This week (after taking a look at the homework) we will continue looking at supervised learning models. Last week, we focused on using *Regression Models* to predict continuous data. We learnt about Simple and Multiple Linear Regression.

This week, we will be learning about *Classification Models*, which are also used in Supervised Learning.

##Classification Models
Classification models are used to assign items to categories, ie, to classify them. Instead of outputing continuous values, classification models output Boolean values: for instance true (1) or false (0). Let's look at how to create a few classification models.

##Logistic Regression
Despite it's name this is a type of classification model. It actually works similar to linear regression, in that instead of fitting a line, the model aims to fit an s-curve.

The result of a logistic regression will be a range between 0 and 1; the closer the number is to 1, the higher the probability that the prediction is true.

Note that this setup would only work to predict two categories (like cat vs dog). If you would like to use this method to predict more than two categories, you can use multinomial logistic regression instead.

Remember when we looked at the titanic dataset? Let's use it to create a model to predict whether or not the students in this class would have survived the titanic!

In [ ]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

import seaborn as sns
df = sns.load_dataset("titanic")

In [ ]:
df.head()

#Remember, before we do anything we need to:
#1)Explore the data
#2)Prepare the data

#We know we want to predict survivors, so why don't you do a boxplot comparing each feature with survived?


#Next, clean the data
#For example, you may want to remove any na values
print(df.isna().sum())
titanicModel = df.dropna()

print("\n\n\nThis df is a little cleaner")
titanicModel.head()
print(titanicModel.isna().sum())

print("\n\n\nIs there a better way to clean the data? Removing all na values might remove quite a bit!")

#You may also want to convert string to numerical values. Here's an easy way to do that
#This is called encoding
titanicModel = pd.get_dummies(titanicModel, columns=['sex'], drop_first=True)

titanicModel.head()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64



This df is a little cleaner
survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64



Is there a better way to clean the data? Removing all na values might remove quite a bit!

,survived,pclass,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,sex_male
1,1,1,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,False
3,1,1,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,False
6,0,1,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True,True
10,1,3,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False,False
11,1,1,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True,False

In [ ]:
#Let's set the features that we want to feed the model, as well as the target prediction

features = ['pclass', 'age', 'sibsp', 'parch', 'fare', 'sex_male']
target = 'survived'

X = titanicModel[features]
y = titanicModel[target]

In [ ]:
#Then, like before, we will split the model

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=16)

In [ ]:
#Fit the model and check out the predictions!

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(y_pred)

[1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1 0 0 0 1 1 0 0 0 1 1 1 0 1 0 0 1 1 0 0 1
 1 0 1 1 1 1 1 1 0]

Great! We have our output (1 for survived, 0 for...did not survive). How can we better represent the data in a way that makes sense?

Now for the fun part! I would like you all to predict the likelyhood of the survival of 6 members of the class, including yourself.

##Decision Trees and Random Forests

For homework, I would like you to look into decision trees and random forests; both theory (for instance, being able to draw a decision tree) as well as implementation. I will expect you to use one or both of these methods to create a model next week!